# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pr:
  branches:
    include:
    - "*"
  paths:
    exclude:
    - README.md

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: ci
  displayName: Build for PR
  condition: eq(variables['Build.Reason'], 'PullRequest')
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
- stage: Release
  displayName: Release Image on Docker Hub
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
    - job: Build
      displayName: Build for release
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'darkorb-dockerhub'
          repository: 'darkorb/exabgp'
          command: 'buildAndPush'
          Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
          tags: |
            $(Build.BuildId)
            latest
            v4