# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- renovate/*
- dev/*

pr:
  branches:
    include:
    - master
    - renovate/*
    - dev/*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
- stage: Release
  displayName: Release Image on Docker Hub
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
    - job: Release
      displayName: Release
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'darkorb-dockerhub'
          repository: 'exabgp'
          command: 'push'
          tags: |
            latest
            v4